package-lock.json
package.json
src/styles/Global.css

어떤 변경 사항이 있나요?
- tailwind CSS install
- 관련 Global.css 파일 수정
- 
- 

env: tailwind CSS 설치 및 환경설정 변동

---

package-lock.json
package.json
src/main.tsx
src/styles/Global.css
src/styles/global.css
tailwind.config.js

어떤 변경 사항이 있나요?
- tailwind css를 v4.1.2에서 v3.4.17로 변경했습니다.
- 팀원들의 tailwind에 대한 경험이나 지식이 부족한 상태
- 25년 1월에 도입된 v4.1.2을 사용하기엔 커뮤니티도, 정보도 부족하여 해당 버전을 사용하기에 무리하다고 판단하여 변경하게 되었습니다.
- 해당 사항 없음

chore: tailwind css v4.1.2 -> v3.4.17로 변경

---

.prettierrc.json
package-lock.json
package.json
postcss.config.cjs
tailwind.config.js
tailwind.config.ts
vite.config.ts

어떤 변경 사항이 있나요?
- tailwind 3.4.17 버전으로 수정함에 따라 autoprefixer, postcss 설치
- tailwind 작성 중 권장 클래스 순서를 자동 정렬 해주는 플러그인 설치
- tailwind.config.js를 tailwind.config.ts로 변경 (typescript 사용 중이므로 해당 사항 권장/오류 방지)
- tailwind/vite 사용 중 남아있던 찌꺼기인 vite.config.ts 내부의 쓸데없는 코드 삭제
- 환경 설정에서 생기는 자잘한 오류로 인해 tailwind css 환경 설정이 적용되지 않아 일부 수정했습니다.
- [tailwind 공식 사이트 using postcss 부분](https://v3.tailwindcss.com/docs/installation/using-postcss)

env, chore: postcss, autoprefixer 플러그인 설치. tailwind 관련 환경 설정 변경

---

src/components/common/Button/BaseButton.tsx
src/components/common/Button/styles.ts
src/types/button.d.ts

어떤 변경 사항이 있나요?
- 버튼에 관한 디자인 시스템 제작하였습니다.
- 해당사항 없음

Button 디자인 시스템 제작

---

index.html
src/assets/icons/ic_x_large.svg
src/components/Modal/BaseModal.tsx
src/components/Modal/ModalOverlay.tsx
src/components/Modal/ModalPortal.tsx
src/components/common/Button/BaseButton.tsx
src/hooks/useModal.ts
src/types/modal.d.ts

어떤 변경 사항이 있나요?
- BaseModal 관련 제작했습니다.
- 추후 로그인 모달, 로그인 유도 모달, 회원 탈퇴 모달도 올리겠습니다.
- 지금은 large 사이즈의 모달만 제작했습니다. props로 small, large로 구분하여 사이즈, 간격에 따라서 제작을 해야할 것 같습니다.

feat: BaseModal 디자인 시스템 제작

---

src/components/common/SearchBar/BasicSearchBar.tsx
src/components/common/SearchBar/MainSearchBar.tsx

어떤 변경 사항이 있나요?
- Search Bar 제작하였습니다.
- 해당 사항 없음

feat: SearchBar 제작

---

public/icons/radioChecked.svg
public/icons/radioUnchecked.svg
src/components/common/Checkbox/BaseCheckbox.tsx
src/components/common/Checkbox/InputCheckbox.tsx
src/components/common/Checkbox/PopupCheckbox.tsx
src/components/common/RadioBtn/BaseRadioBtn.tsx
src/types/checkbox.d.ts

어떤 변경 사항이 있나요?
- Checkbox와 Radio Button 제작했습니다
- Radio Button이 얼마 없어서 같이 커밋할게요!

feat: Checkbox & RadioBtn 제작

---

src/components/common/Tag/BaseBadge.tsx
src/components/common/Tag/BaseTag.tsx
src/components/common/Tag/style.ts
src/styles/types/tag.d.ts
src/types/tag.d.ts
tailwind.config.ts

어떤 변경 사항이 있나요?
- Tag & Badge 디자인시스템 제작했습니다.
- Badge를 뒤늦게 봐서 제작하는 바람에 부득이하게 커밋을 2개 제작했습니다.

Tag&Badge 제작

---

src/components/common/Tag/BaseTag.tsx
src/components/common/Tag/style.ts
src/types/tag.d.ts

어떤 변경 사항이 있나요?
- Tag 디자인 시스템 폰트 수정했습니다.
- Tag 디자인시스템 중에서 size가 large이고 type이 filled인 폰트는 Caption/13_Sb600인 것을 놓쳐서 수정했습니다.
- 해당 사항 없음

design: tag 폰트 수정

---

package-lock.json
package.json

어떤 변경 사항이 있나요?
- tanstack/react-query, zustand 설치했습니다.
- 리뷰어가 중점적으로 봐줬으면 좋겠는 부분이 있으면 적어주세요.
- 논의해야할 부분이 있다면 적어주세요.
- ex) 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 있을까요?

chore: tanstack/react-query, zustand 설치

---

src/components/Main/Card.tsx
src/components/SkillIcons.tsx
src/utils/getSkillIcon.ts

어떤 변경 사항이 있나요?
- Card 내에 skill 아이콘 제작했습니다.
- 백엔드에서 보내주는 skill display_name을 파일경로에 변수로 넣었습니다.
- SkillIcon 컴포넌트에 iconKeys props에는 배열 타입으로 skill의 이름을, size props에는 small이나 large를 넣어주시면 됩니다.
- 추후 정민님과 reference를 맞추고 파일 경로들을 수정하면 다른 아이콘들도 나올 것 같습니다.

feat: skill icon 제작

---

src/api/projectPost.ts
src/constants/endpoint.ts

어떤 변경 사항이 있나요?
- endpoint 파일에서 /api prefix를 수정했습니다.
- 401 에러가 해결돼서 프로젝트 게시글 조회에 쓰이는 axiosInstance를 axios로 변경하였습니다.
- 리뷰어가 중점적으로 봐줬으면 좋겠는 부분이 있으면 적어주세요.
- 논의해야할 부분이 있다면 적어주세요.
- ex) 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 있을까요?

fix: /api prefix 제거 및 프로젝트 게시물 조회 관련 수정

---

src/components/common/IconWrapper/BookmarkWrapper.tsx

어떤 변경 사항이 있나요?
- BookmarkWrapper api 연결했습니다.
- 리뷰어가 중점적으로 봐줬으면 좋겠는 부분이 있으면 적어주세요.
- 논의해야할 부분이 있다면 적어주세요.
- ex) 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 있을까요?

fix: BookmarkWrapper api 연결

---

src/components/common/Chip/KeywordChip/KeywordChip.tsx
src/components/common/InputBox/BasicTextArea/BaseBasicTextArea.tsx
src/components/common/InputBox/KeywordTextArea/KeywordTextArea.tsx
src/components/common/Select/BaseSelect.tsx
src/types/BasicTextArea.d.ts
src/types/Select.d.ts

- API와 연결했을 때 일부 컴포넌트가 작동되지 않는 현상을 해결했습니다.
- 모집글 작성을 확인했을 때, 해당 부분에 아이디 검색이 있는 것을 확인해, KeywordChip과 KeywordTextArea가 Skill 전용 컴포넌트처럼 사용되던 현상을 수정했습니다.

refactor: 컴포넌트 수정

---

src/constants/endpoint.ts

어떤 변경 사항이 있나요?
- 백엔드 수정사항에 따라 POST, USER_PROFILE_IMAGE 엔드포인트 추가해두었습니다.

feat: USER_PROFILE_IMAGE Endpoint 추가

---

src/components/common/Select/SelectTextIn.tsx
src/components/common/Select/styles.ts
src/types/SelectTextIn.d.ts

어떤 변경 사항이 있나요?
SelectTextIn를 제작했습니다.

feat: SelectTextIn

---

src/App.tsx
src/api/user.ts
src/components/Profile/IpnList.tsx
src/components/Profile/ProfileInfo.tsx
src/components/Profile/ProfileTag.tsx
src/hooks/useUserProfile.ts
src/pages/Profile.tsx

어떤 변경 사항이 있나요?
- 프로필 보기 페이지를 제작했습니다.
- 우선적으로 path를 (1) 내 프로필 : /Profile (2) 타인의 프로필 : /Profile/:id 로 제작했으나, 내 활동(관심목록, 지원현황, 내 작성글)과 타인의 프로필이 구분되어야 하는 것을 생각해서 경로를 수정해야 할 것 같습니다.
- 좋아요/following 관련 api는 아직 연결되지 않았습니다.
- component/profile/IpnList.tsx 의 네비게이션이 아직 경로가 지정되지 않았으므로 작성되지 않았습니다.
- Profile 페이지가 확장됨에 따라 컴포넌트를 분리할 생각입니다.

feat: Profile 페이지 (프로필 보기 페이지) 제작

---

src/components/common/InputBox/BasicTextArea/BaseBasicTextArea.tsx
src/components/common/InputBox/IconTextArea/BaseIconTextArea.tsx
src/pages/ProfileForm.tsx
src/types/BasicTextArea.d.ts
src/types/IconTextArea.d.ts

어떤 변경 사항이 있나요?
- IconTextArea, BasicTextArea 글자수제한 이슈 수정했습니다.
- 주석으로 사용 설명을 덧붙여두었습니다.

feat, refactor: IconTextArea, BasicTextArea 수정

---

src/api/follow.ts
src/components/Profile/FollowBtn.tsx
src/constants/endpoint.ts
src/hooks/useFollow.ts
src/pages/Profile.tsx
src/stores/followStore.ts
src/types/user.ts

어떤 변경 사항이 있나요?
- Follow 기능을 추가했습니다.
- positions를 배열로 수정했습니다.
- follow 수 집계가 개인의 것만 가능해 해당 부분 api가 완성되었을 시 수정할 예정입니다.

feat: follow 기능 추가

---

src/App.tsx
src/api/projectPost.ts
src/components/PostForm/CurrentPositionField.tsx
src/components/PostForm/RemainingPositionField.tsx
src/components/common/InputBox/IconTextArea/CalendarIconTextArea.tsx
src/hooks/useProjectPost.ts
src/pages/PostForm.tsx

어떤 변경 사항이 있나요?
- 모집글 작성 페이지 제작했습니다.
- 아이디 검색 기능 등 서버 쪽 개발 완료되면 수정하도록 하겠습니다.

feat: 모집글 작성 페이지 제작

---

src/App.tsx
src/components/Profile/IpnList.tsx
src/components/common/Tab/FolderTab.tsx
src/components/common/Tab/FolderTabGroup.tsx
src/components/common/Table/Table.tsx
src/components/common/Table/TableCell.tsx
src/constants/ProfileTabConfig.ts
src/constants/endpoint.ts
src/constants/route.ts
src/hooks/useFollowerCount.ts
src/hooks/useNavigation.ts
src/pages/profile/ProfileApplications.tsx
src/pages/profile/ProfileHome.tsx
src/pages/profile/ProfileLayout.tsx
src/pages/profile/ProfileLikes.tsx
src/pages/profile/ProfilePosts.tsx
src/routes/ProfileRoute.tsx
src/stores/userStore.ts
src/types/ProfileApi.d.ts
src/utils/profileTableRowMapper.tsx

어떤 변경 사항이 있나요?
- Profile Page 분리 (Home, Likes, Applications, Posts) / Routes 역시 추가했으나, 임시적인 분리로 기능이 완벽히 추가가 되지 않았습니다. 추후 수정될 예정입니다.
- Profile Table 제작
- 특정 유저의 Follower 집계
- Table 제작에 대한 코멘트가 있습니다.
- Applications, Likes, Posts에 중복된 코드가 있습니다. Table의 UI가 같지만, 기능 충돌과 복잡성을 고려해서 분리해뒀습니다. 간편성을 위해 컴포넌트 분리를 원하신다면 컴포넌트를 분리해 수정한 후 올려두도록 하겠습니다.
- ProfileApplications, Likes, Posts에 dummyData로 데이터를 넣어뒀습니다. Api에 따라 ProfileApi파일 등 수정해서 사용하면 될 것 같습니다.
- 최대한 기능 추가 및 보수가 용이하도록 제작했으나 모든 상황을 고려할 수 없었으므로 부족한 부분이 있을 수 있습니다. 자유로운 수정과 보수가 가능합니다.

feat: Profile 기능 추가 및 Table 제작

---

src/components/common/InputBox/IconTextArea/CalendarIconTextArea.tsx
src/styles/global.css

어떤 변경 사항이 있나요?
- Calendar 내에 숫자만 입력해도 하이폰이 붙게 수정했습니다.
- Calendar 내에 disabled 관련 폰트 색상 수정했습니다.
- 리뷰어가 중점적으로 봐줬으면 좋겠는 부분이 있으면 적어주세요.
- 논의해야할 부분이 있다면 적어주세요.
- ex) 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 있을까요?

Calendar 관련 코드 수정했습니다.
